name: Code Documenter Workflow

on:
  workflow_dispatch:
  #pull_request:
  #  types: [opened, synchronize]

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  generate_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Authenticate with Keycloak
        id: keycloak_auth
        run: |
          TOKEN_RESPONSE=$(curl -s -X POST 'http://auth.gftaiimpact.local/realms/ai-impact/protocol/openid-connect/token' \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -d 'client_id=ai-impact-client' \
            -d "username=administrator" \
            -d "password=Gft@2025" \
            -d "scope=openid" \
            -d "grant_type=password")

          ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')

          if [ -z "$ACCESS_TOKEN" ] || [ "$ACCESS_TOKEN" == "null" ]; then
            echo "Failed to obtain access token"
            echo "$TOKEN_RESPONSE"
            exit 1
          fi

          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Install Node.js dependencies
        run: npm install axios form-data dotenv

      - name: Create Classes List
        id: changes
        run: node codeDocumenter/generate-files-list.js

      - name: Prepare and Send to API (TestCreator)
        id: send_api
        run: node codeDocumenter/send-files.js

      - name: Save Generated Tests
        run: node codeDocumenter/download-files.js

      - name: Criar Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Add generated Unit Tests"
          title: "Testes unitários gerados automaticamente"
          body: "Este PR contém Testes Unitários gerados pela Wynnx."
          branch: "tests-$(git rev-parse --short HEAD)-$(date +%Y%m%d-%H%M%S)"
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          labels: "auto-generated, testes"
          draft: false
